#!/usr/bin/env php
<?php


use ConsoleCommands\PublishCommand;
use Symfony\Component\Console\Application;

if (file_exists(dirname(__FILE__) . '/vendor/autoload.php')) {
    require_once dirname(__FILE__) . '/vendor/autoload.php';
}


$application = new Application();

// Register commands
$application->add(new PublishCommand());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}
